language: node_js
node_js:
  - "node"

cache: npm

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  fqdn: percolation.yetanother.one
  on:
    branch: master

notifications:
  email: false
